# docker-compose.yml
services:
  reviewpyper-api:
    image: calvinwhow/reviewpyper_api:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: reviewpyper_api/containers/Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      DATA_DIR: /data
    volumes:
      - ./reviewpyper_api/local_data:/data
