services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - gateway

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./data:/data
    environment:
      - REVIEWPYPER_API_URL=http://reviewpyper-api:8000
      - DATA_DIR=/data
    depends_on:
      - reviewpyper-api

  reviewpyper-api:
    platform: linux/amd64
    build:
      context: ./containers
      dockerfile: reviewpyper-api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
